#
# nixfont — fonts as a shared concern, not a corner of somebody else's module.
#
# WHY ITS OWN MODULE. Fonts are consumed by four unrelated domains at once: the terminal wants a
# nerd/mono family, the desktop UI wants a sans, documents want metric-compatible families, and
# PRINTING wants gsfonts because ghostscript needs it for PostScript. If an office module owned
# fonts, a desktop module would have to depend on the office module to get its UI font -- and a
# headless box rendering PDFs would have to pull in a desktop it does not have. So fonts are a
# dependency OF those modules rather than owned by any one of them.
#
# It is also more than a package list: the useful part is telling fontconfig which family is the
# default sans, serif and monospace, which is real generated config.
{ config, lib, ... }:
let
  cfg = config.nixfont;
  catalogue = import ../lib/fonts.nix { };

  mkGroup = what: table: lib.mkOption {
    type = lib.types.listOf (lib.types.enum (lib.attrNames table));
    default = [ ];
    description = "Which ${what} to install. Available: ${lib.concatStringsSep ", " (lib.attrNames table)}.";
  };

  selected = lib.flatten [
    (map (k: catalogue.ui.${k}) cfg.ui)
    (map (k: catalogue.mono.${k}) cfg.mono)
    (map (k: catalogue.document.${k}) cfg.document)
    (map (k: catalogue.coverage.${k}) cfg.coverage)
  ];

  # fontconfig's <alias> blocks: what "sans-serif" and friends actually resolve to. Written only
  # for the families the host asked for -- naming a default this host did not install is how you
  # get silent fallback to whatever fontconfig picks alphabetically.
  aliasFor = generic: family: lib.optionalString (family != null) ''
      <alias>
        <family>${generic}</family>
        <prefer><family>${family}</family></prefer>
      </alias>
  '';
in
{
  options.nixfont = {
    ui = mkGroup "interface fonts" catalogue.ui;
    mono = mkGroup "monospace/terminal fonts" catalogue.mono;
    document = mkGroup "document and print-compatibility fonts" catalogue.document;
    coverage = mkGroup "Unicode coverage fonts" catalogue.coverage;

    defaults = {
      sans = lib.mkOption {
        type = lib.types.nullOr lib.types.str;
        default = null;
        description = "Family name fontconfig resolves `sans-serif` to, e.g. \"Inter\". Null leaves fontconfig's own default alone.";
      };
      serif = lib.mkOption {
        type = lib.types.nullOr lib.types.str;
        default = null;
        description = "Family name for `serif`.";
      };
      monospace = lib.mkOption {
        type = lib.types.nullOr lib.types.str;
        default = null;
        description = "Family name for `monospace`, e.g. \"GeistMono Nerd Font\".";
      };
      emoji = lib.mkOption {
        type = lib.types.nullOr lib.types.str;
        default = null;
        description = "Family appended as a last-resort fallback for every generic, so emoji render instead of tofu.";
      };
    };

    fontconfig = lib.mkOption {
      type = lib.types.lines;
      readOnly = true;
      description = "Generated fontconfig fragment. Both backends write this to the platform's conf.d.";
    };

    archPackages = lib.mkOption {
      type = lib.types.listOf lib.types.str;
      readOnly = true;
      description = "Selected fonts as pacman package names, for a host's own reconciler to consume.";
    };

    aurPackages = lib.mkOption {
      type = lib.types.listOf lib.types.str;
      readOnly = true;
      description = ''
        Selections that live in the AUR rather than an official repo, kept SEPARATE because
        `pacman -S` cannot resolve them -- it fails the whole transaction with "target not found",
        which takes the rest of the converge down with it. Wire them to the AUR side:

          nixarch.packages.aur = config.nixfont.aurPackages;

        With no `aurUser` configured the reconciler skips them with a warning, which is the right
        failure mode: the packages stay as they are and nothing else breaks.
      '';
    };

    unavailableOnNixos = lib.mkOption {
      type = lib.types.listOf lib.types.str;
      readOnly = true;
      description = "Selections with no nixpkgs equivalent, surfaced rather than silently dropped.";
    };
  };

  config = {
    nixfont.archPackages = lib.unique (map (f: f.arch) (lib.filter (f: !(f.aur or false)) selected));
    nixfont.aurPackages = lib.unique (map (f: f.arch) (lib.filter (f: f.aur or false) selected));
    nixfont.unavailableOnNixos =
      lib.unique (map (f: f.arch) (lib.filter (f: f.nixpkgs == null) selected));

    nixfont.fontconfig = ''
      <?xml version="1.0"?>
      <!DOCTYPE fontconfig SYSTEM "urn:fontconfig:fonts.dtd">
      <!-- Generated by nixfont. Do not edit. -->
      <fontconfig>
      ${aliasFor "sans-serif" cfg.defaults.sans}${aliasFor "serif" cfg.defaults.serif}${aliasFor "monospace" cfg.defaults.monospace}${lib.optionalString (cfg.defaults.emoji != null) ''
      ${lib.concatMapStringsSep "\n" (g: ''
        <alias>
          <family>${g}</family>
          <accept><family>${cfg.defaults.emoji}</family></accept>
        </alias>'') [ "sans-serif" "serif" "monospace" ]}
      ''}</fontconfig>
    '';
  };
}
